
.. _core-developers-team:


.. raw:: html

    <div class="team-grid">

    <div class="team-member">
        <img
        src="https://avatars.githubusercontent.com/u/48806417?v=4"
        alt="Avatar picture of @JoaoPeriquito"
        class="team-avatar"
        />
        <a href="https://github.com/JoaoPeriquito" class="team-name">Joao Periquito</a>
        <div class="team-handle">@JoaoPeriquito</div>
    </div>

    <div class="team-member">
        <img
        src="https://avatars.githubusercontent.com/u/6051075?v=4"
        alt="Avatar picture of @plaresmedima"
        class="team-avatar"
        />
        <a href="https://github.com/plaresmedima" class="team-name">Steven Sourbron</a>
        <div class="team-handle">@plaresmedima</div>
    </div>

    <!-- Add more team members here -->
    </div>
