
.. _core-developers-team:


Maintainers:


.. raw:: html

   <div class="team-member">
     <a href="https://github.com/plaresmedima" class="team-member-name">
        <div class="team-member-photo">
           <img
             src="https://avatars.githubusercontent.com/u/6051075?v=4"
             loading="lazy"
             alt="Avatar picture of @plaresmedima"
           />
        </div>
        Steven Sourbron
     </a>
     <div class="team-member-handle">@plaresmedima</div>
   </div>


